
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwdtqctvqypjtnkwgwxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZHRxY3R2cXlwanRua3dnd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTY4MjcsImV4cCI6MjA1ODIzMjgyN30.rMmPM9u1_aU4502urYiO2ZF_5J-l6fvffxi7t4fYxvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
