// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdvmzijhtelwfmpsbnyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdm16aWpodGVsd2ZtcHNibnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzgzMzYsImV4cCI6MjA1ODA1NDMzNn0.XcKm6ddS1CXB_HUKmoQL-MEt4TgccMy7KqiS22A6nfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);